name: CD Pipeline

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Minikube
      - name: Set up Minikube
        uses: manusa/actions-setup-minikube@v2
        with:
          minikube-version: 'latest'

      # Deploy the application
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f kubernetes/deployment.yml
          kubectl apply -f kubernetes/service.yml
